### ISSUE TITLE
Formatting docstrings

### ISSUE THREAD

**Issue by ccurtis7** [mdbresh/HyperUnmixing#5]
Great job with your first set of functions. A few formatting tips:

You shoudl cut back on spaces. You only need spaces in between sections, but not between headings and lines underneath, for instance. One space is fine between sections.

https://github.com/mdbresh/HyperUnmixing/blob/b8b267e459689582b6be0bb983b1e56e7990c925/Wav_2_Im.py#L3-L29

**Comment by caitlin-cornell23** [comment]
Fixed spaces in the docstring for Wav_2_Im.py on the master branch in the folder HyperUnmixing
