### ISSUE TITLE
Start organizing functions into modules.

### ISSUE THREAD

**Issue by ccurtis7** [mdbresh/HyperUnmixing#6]
I see some of your functions on each of your branches. I suggest to start thinking of a way to structure your project into modules. Modules are groups of related functions all stored together in the same `.py` file-- think of the `skimage` package as an example. It has `transform` and `filter` and `morphology` modules.  Typically, all `.py` files associate with a project are stored in a sub-directory with the same name as the repo.

**Comment by preethampaul** [comment]
All the function files are placed in a folder with name "HyperUnmixing". A __init__.py file is placed to call the functions directly by just importing the folder.

from .img_util import *
from .normalization import *
from .pca_util import *
from .sample import *
from .Wav_2_Im import *

This can be updated as more files are added to this folder.
