### ISSUE TITLE
Store development notebooks in a sub-directory

### ISSUE THREAD

**Issue by ccurtis7** [mdbresh/HyperUnmixing#7]
A similar note on developmental notebooks. You should have a dedicated folder on each branch to hold all the notebooks used to develop the code. It's also a good idea to name them with the date included to keep them organized chronologically e.g. `04_25_20_preprocessing_development.ipynb`.

**Comment by mdbresh** [comment]
dedicated folder for development notebooks made on "master" and "maddie" branches.
